### ISSUE TITLE
哈喽, 看到你写的博客挺不错的, 另外也看到你 star 了 jzero 项目

### ISSUE THREAD

**Issue by jaronnie** [liushun-ing/liushun-ing.github.io#1]
想问问你有没有在使用 [jzero](https://github.com/jzero-io/jzero), 可以沟通一下, 对于区块链的话，我以前就是从事区块链行业，也可以交流一下

**Comment by liushunkkk** [comment]
哈哈，我是研究院的实习生，组长推荐了jzero，就学习了一下

**Comment by jaronnie** [comment]
哦哦, 趣链那个研究院？组长是威锋老大嘛

**Comment by liushunkkk** [comment]
是的hhh

**Comment by jaronnie** [comment]
难怪 你现在才来实习？
之前我领导也让我去来着 我给拒了
